from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('bio_content_url', models.TextField(blank=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ['order', '-published_at']},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={'verbose_name_plural': 'categories', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_expiretime', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('source', models.CharField(default='website', max_length=80)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('content_url', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(max_length=160)),
                ('time_slot', models.CharField(blank=True, max_length=120)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=120)),
            ],
            options={'ordering': ['-date', '-published_at']},
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('content_url', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('place', models.CharField(blank=True, max_length=160)),
                ('time_to_read', models.PositiveIntegerField(default=8)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_insights', to='cms.author')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='cms.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='cms.category')),
            ],
            options={'ordering': ['-date', '-published_at']},
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_url', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.event')),
            ],
            options={'ordering': ['position', 'id']},
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.speaker')),
            ],
            options={'ordering': ['position'], 'unique_together': {('event', 'speaker')}},
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', through='cms.EventSpeaker', to='cms.speaker'),
        ),
        migrations.CreateModel(
            name='InsightMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('media_url', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.insight')),
            ],
            options={'ordering': ['position', 'id']},
        ),
        migrations.CreateModel(
            name='InsightLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cms.insight')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_likes', to='cms.subscriber')),
            ],
            options={'unique_together': {('insight', 'subscriber')}},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=40)),
                ('content_id', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='visible', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cms.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('interests', models.CharField(blank=True, max_length=240)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_expire_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verify_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cms.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
