# Generated by Django 5.0.6 on 2026-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='media_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insightmedia',
            name='media_url',
            field=models.TextField(),
        ),
    ]
