# Generated by Django 5.0.6 on 2026-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_category_description_event_end_time_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='image_note',
            field=models.TextField(blank=True),
        ),
    ]
