from django.urls import path

from .views import (
    CmsBannerCollectionView,
    CmsAuthorCollectionView,
    CmsCategoryCollectionView,
    CmsConfigView,
    CmsDashboardView,
    CmsEventActionView,
    CmsEventCollectionView,
    CmsEventScheduleCreateView,
    CmsEventSpeakerCreateView,
    CmsInsightActionView,
    CmsInsightCollectionView,
    CmsInsightDetailView,
    CmsLoginView,
    CmsLookupView,
    CmsMeView,
    CmsSpeakerCollectionView,
    CmsUserCollectionView,
    EventDetailView,
    EventRegistrationCreateView,
    EventListView,
    HomepageView,
    InsightCommentCreateView,
    InsightDetailView,
    InsightLikeCreateView,
    InsightListView,
    ContactMessageCreateView,
    SubscriberCreateView,
)

urlpatterns = [
    path('homepage/', HomepageView.as_view(), name='homepage'),
    path('insights/', InsightListView.as_view(), name='insight-list'),
    path('insights/<slug:slug>/', InsightDetailView.as_view(), name='insight-detail'),
    path('insights/<slug:slug>/comments/', InsightCommentCreateView.as_view(), name='insight-comment-create'),
    path('insights/<slug:slug>/likes/', InsightLikeCreateView.as_view(), name='insight-like-create'),
    path('events/', EventListView.as_view(), name='event-list'),
    path('events/<slug:slug>/', EventDetailView.as_view(), name='event-detail'),
    path('events/<slug:slug>/registrations/', EventRegistrationCreateView.as_view(), name='event-registration-create'),
    path('subscribers/', SubscriberCreateView.as_view(), name='subscriber-create'),
    path('contact-messages/', ContactMessageCreateView.as_view(), name='contact-message-create'),
    path('cms/login/', CmsLoginView.as_view(), name='cms-login'),
    path('cms/me/', CmsMeView.as_view(), name='cms-me'),
    path('cms/config/', CmsConfigView.as_view(), name='cms-config'),
    path('cms/dashboard/', CmsDashboardView.as_view(), name='cms-dashboard'),
    path('cms/lookups/', CmsLookupView.as_view(), name='cms-lookups'),
    path('cms/insights/', CmsInsightCollectionView.as_view(), name='cms-insight-collection'),
    path('cms/insights/<int:pk>/', CmsInsightDetailView.as_view(), name='cms-insight-detail'),
    path('cms/insights/<int:pk>/<str:action>/', CmsInsightActionView.as_view(), name='cms-insight-action'),
    path('cms/events/', CmsEventCollectionView.as_view(), name='cms-event-collection'),
    path('cms/events/<int:pk>/<str:action>/', CmsEventActionView.as_view(), name='cms-event-action'),
    path('cms/event-speakers/', CmsEventSpeakerCreateView.as_view(), name='cms-event-speaker-create'),
    path('cms/event-schedules/', CmsEventScheduleCreateView.as_view(), name='cms-event-schedule-create'),
    path('cms/banners/', CmsBannerCollectionView.as_view(), name='cms-banner-collection'),
    path('cms/categories/', CmsCategoryCollectionView.as_view(), name='cms-category-collection'),
    path('cms/authors/', CmsAuthorCollectionView.as_view(), name='cms-author-collection'),
    path('cms/speakers/', CmsSpeakerCollectionView.as_view(), name='cms-speaker-collection'),
    path('cms/users/', CmsUserCollectionView.as_view(), name='cms-user-collection'),
]
